#' @importFrom digest digest
#' @importFrom stringi stri_detect_fixed
#'
#' @title Author checker
#' @name author_check
#'
#' @param name Initials of the code's author name. (Last name, first name)
#' @param credentials Dataframe with the hash code of the tutor. Can be loaded via 'get_credentials' function.
#' @param hash_col Name of the column with hash codes. Default is "HASH"
#'
#' @description
#' Function to check if the name of an author is in a database of validated credentials. Credentials in a database must be stored as HASH. Hash generated by the function uses the following arguments: digest(text, algo= 'sha512', serialize=F). The function is planned to be used by future code implementations.
#'
#' @return Text in console whether the statistical analysis is authorized by a tutor or not
#'
#' @examples
#'
#' library(digest)
#'
#'
#'hashcred1 <- digest("JAFG",
#'algo = "sha512",
#'serialize = FALSE)
#'
#'credentials <- data.frame(
#'HASH = hashcred1,
#'ID = c("JAFG"))
#'
#'auth_outp <- author_check("JAFG",
#'credentials = credentials,
#'hash_col = "HASH")
#'
#'
#' @export

author_check<-function(name, credentials, hash_col = "HASH"){

  namehash<- digest(name, algo = "sha512", serialize = FALSE)

    if(is.data.frame(credentials)){
      if(any(stringi::stri_detect_fixed(credentials[[hash_col]], pattern = namehash))){

        text_outp <- ("Statistical analysis is authentic")
        text_outp
      } else {
        text_outp <- c("Statistical analysis is not authentic Please check with your tutor or committee")
        text_outp
      }
    } else {
      stop("Credentials data must be a dataframe")
    }
}

#' @title Get credentials for author check
#' @name get_credentials
#' @param data Name of the file which the credentials are stored.
#' @param sep Separator of the dataframe. Default is "," to denote a .csv file.
#'
#' @return A dataframe with authorization credentials
#'
#' @examples
#' \dontrun{
#' credentials<-get_credentials(data = "googlesheets_url", sep=",")}
#'

get_credentials<-function(data=NULL, sep=","){
  if(is.null(data)){
    stop("Credentials database should be a dataframe")
  }
  credentials<-read.delim(data, sep=sep)
  credentials
}
